### ISSUE TITLE
Learn資料作成_Ansibleとの連携（実習編）

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation-docs#10]
Learn資料作成とコミュニティサイトへの反映

●Ansible-driver 実習編の資料作成
以下の4編を作成予定
①Ansible-driver　概要／共通
②Ansible-Legacy
③Ansible-LegacyRole
④Ansible-Pioneer

**Comment by ryohei-nako** [comment]
作成。リリース済み
