### ISSUE TITLE
[docs]【管理コンソール】シーケンスを調整するメニューを追加する

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation-docs#133]
[【管理コンソール】シーケンスを調整するメニューを追加する #180](https://github.com/exastro-suite/it-automation/issues/180)

**Comment by Saito-Masaru** [comment]
変更内容
* P1 版を更新
* 目次更新
* P5 一覧を更新
* P28 シーケンス管理のページを追加
