### ISSUE TITLE
[docs]【共通】各作業管理メニューからスコアを削除

### ISSUE THREAD

**Issue by ooif** [exastro-suite/it-automation-docs#137]
[【共通】各作業管理メニューからスコアを削除](https://github.com/exastro-suite/it-automation/issues/353)

**Comment by TakashiKitamori** [comment]
**変更箇所**
Exastro-ITA_利用手順マニュアル_Ansible-driver
> 5.3.13 作業管理

Exastro-ITA_利用手順マニュアル_OpenStack-driver
> 4.1.3 画面説明（6）結果管理

Exastro-ITA_利用手順マニュアル_Terraform-driver

> 6.2.15 作業管理

Exastro-ITA_利用手順マニュアル_Symphony
> 4.1.6 Symphony作業一覧
