### ISSUE TITLE
Learn資料修正_Exastro IT Automation BASE（座学編）

### ISSUE THREAD

**Issue by ta-matsuo** [exastro-suite/it-automation-docs#17]
P19
Movement、オペレーション、対象機器がすべてA、B、Cと採番されているのでわかりずらい。
1,2,3とかX,Y,Zとかそれぞれ別の採番をして欲しい。

**Comment by j-kumamoto** [comment]
●修正候補
「A/Bが設定されます」「Cが設定されます」はそれぞれの対象機器A/BとCを示している。
→　「Movement」と「オペレーション」をA、B、C以外に書き換える。

**Comment by kouhei-suzuki** [comment]
「Movement」を1、2、3「オペレーション」をX、Y、Zの採番に修正。
修正版をv.1.4で公開予定

**Comment by j-kumamoto** [comment]
↑ 上記は1.4.0で払い戻し済み・公開済。

**Comment by kouhei-suzuki** [comment]
"エクスポート/インポート"機能が新たなメニューグループとなったので、
マニュアル内の"エクスポート/インポート"機能に関する記述について修正中

●修正中ドキュメント
ITA-base_classroom lecture_ja.pptx
ITA-base_classroom lecture_ja.pdf

**Comment by ryohei-nako** [comment]
新しいissue&60に統合、クローズ
