### ISSUE TITLE
[docs]【Ansible-Driver】アクセス許可ロールを使用している場合、代入値自動登録設定とパラメータシートの組み合わせにより作成するべきではないデータが作成される

### ISSUE THREAD

**Issue by ooif** [exastro-suite/it-automation-docs#198]
[【Ansible-Driver】アクセス許可ロールを使用している場合、代入値自動登録設定とパラメータシートの組み合わせにより作成するべきではないデータが作成される](https://github.com/exastro-suite/it-automation/issues/525)

**Comment by enoman** [comment]
完了
