### ISSUE TITLE
[docs]【Terraform-Driver】アクセス許可ロールを使用している場合、代入値自動登録設定とパラメータシートの組み合わせにより作成するべきではないデータが作成される

### ISSUE THREAD

**Issue by ooif** [exastro-suite/it-automation-docs#199]
[【Terraform-Driver】アクセス許可ロールを使用している場合、代入値自動登録設定とパラメータシートの組み合わせにより作成するべきではないデータが作成される](https://github.com/exastro-suite/it-automation/issues/526)

**Comment by HibikiNanri** [comment]
マージ済み
