### ISSUE TITLE
[docs]【Ansible-driver】読替表の命名規則の注記追加

### ISSUE THREAD

**Issue by ryohei-nako** [exastro-suite/it-automation-docs#208]
85ページ目、【6.3 ロールパッケージ（Ansible-Legacy Role）の記述】について
読替表の命名則がこのページにしか書いておらず、わかりにくくなっている。

 
【6.5 読替表（Ansible-Legacy Role のみ）の記述】の【(2) 注意事項】の欄に記載が適当かと思いますので追記をお願したく。

**Comment by enoman** [comment]
完了
