### ISSUE TITLE
［docs］【メニュー作成】ファイル埋込変数名とテンプレート埋込変数名をプルダウン選択対象とする 

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation-docs#21]
以下開発に関するドキュメント修正

【メニュー作成】ファイル埋込変数名とテンプレート埋込変数名をプルダウン選択対象とする #123
(https://github.com/exastro-suite/it-automation/issues/123)

**Comment by enoman** [comment]
1.5で対応済み
