### ISSUE TITLE
【Documents】AWS ECSベースのCI/CD図にいくつかの改善ポイント

### ISSUE THREAD

**Issue by kubo-1** [exastro-suite/it-automation-docs#267]
https://exastro-suite.github.io/docs/asset/pdf/exastro_outline_ja.pdf
のスライド72の改善ポイント
・”システム”の領域を2種類に分割(CodeDeployからのデプロイ対象/CFnからのデプロイ対象)
・全般的にExastro ITAからのシステム変更をCFn等での高度化

**Comment by katokeita** [comment]
変更箇所の翻訳をお願いします。
![image](https://user-images.githubusercontent.com/49501166/107724315-f023e080-6d26-11eb-83f5-81896ccdb5da.png)

|変更前|変更後|
|---|---|
|Playbook|CFn Template（Ansible変数化）|
|変更手順（命令型IaC）|CFn Template（宣言型IaC）|
|データ形状等の変更（e.g. DBカラム追加）|Stack変更（e.g. DBカラム追加）|
|自動化ソフトウェアはTerraformも利用が可能|CFnをAnsible-Playbookを使って適用する前提の表現をしているが、他の手段としては以下のようなものがある<br>●Ansible-Playbookで命令型の自動化を活用<br>●Terraformで宣言型の自動化を活用する<br>（他のパブリッククラウドと連携するようなケースに有効）|

**Comment by JoachimLarsen** [comment]
お待たせしております。
訳文はこちらを使いください。

変更後 | 訳文
-- | --
CFn   Template（Ansible変数化） | CFn Template (Partly variablized   to Ansible)
CFn   Template（宣言型IaC） | CFn Template (Declarative IaC)
Stack変更（e.g.   DBカラム追加） | Change stack (e.g. Add DB   Collumn)
CFnをAnsible-Playbookを使って適用する前提の表現をしているが、他の手段としては以下のようなものがある | Here, we use Ansible-Playbook to   apply CFn, but it is also possible to use the following methods:
●Ansible-Playbookで命令型の自動化を活用 | ●Using Imperative automation   with Ansible-Playbook
●Terraformで宣言型の自動化を活用する | ●Using Declarative automation   with Terraform
（他のパブリッククラウドと連携するようなケースに有効） | (Useful for cases where you want   to integrate with other public clouds).
