### ISSUE TITLE
【Document】ITAのHA構成インストールマニュアルの不備

### ISSUE THREAD

**Issue by kenshirotanaka08** [exastro-suite/it-automation-docs#278]
下記のインストールマニュアルにいくつか不備があります。
https://exastro-suite.github.io/it-automation-docs/learn_ja.html

1．SELINUX無効化の手順が無い
2．backyard手順のNo.36～46のパス
・/（インストール資材展開先）/it-automation-x.x.x/ita_install_package/list/×××.txt→誤（現在の記載）
・/（インストール資材展開先）/it-automation-x.x.x/ita_install_package/ITA/list/×××.txt→正

**Comment by sinatommy** [comment]
1．SELINUX無効化の手順が無い　→インストールするサーバ自体の設定なので、インストーラでは変更しない。
