### ISSUE TITLE
[docs]【全般】select countの定義があるVIEWのデータに対してアクセス許可ロールによるデータ絞り込みの対応

### ISSUE THREAD

**Issue by ooif** [exastro-suite/it-automation-docs#287]
[【全般】select countの定義があるVIEWのデータに対してアクセス許可ロールによるデータ絞り込みの対応](https://github.com/exastro-suite/it-automation/issues/559)

**Comment by enoman** [comment]
変更点なし

**Comment by enoman** [comment]
変更箇所なし
