### ISSUE TITLE
[docs]【Ansible-Driver】Pioneerのcommandモジュールをcommand・promptだけの記述で使用した場合、プロンプト待ちでタイムアウトが発生する。

### ISSUE THREAD

**Issue by ooif** [exastro-suite/it-automation-docs#336]
[【Ansible-Driver】Pioneerのcommandモジュールをcommand・promptだけの記述で使用した場合、プロンプト待ちでタイムアウトが発生する。](https://github.com/exastro-suite/it-automation/issues/832)

**Comment by enoman** [comment]
完了
