### ISSUE TITLE
[docs]【Ansible-Driver】Pioneer作業実行時、対話ファイルのYAML文法に不備がある場合のエラーメッセージ改善

### ISSUE THREAD

**Issue by ooif** [exastro-suite/it-automation-docs#343]
[【Ansible-Driver】Pioneer作業実行時、対話ファイルのYAML文法に不備がある場合のエラーメッセージ改善(https://github.com/exastro-suite/it-automation/issues/842)

**Comment by enoman** [comment]
完了
