### ISSUE TITLE
【Learn】_v1.7.1_Exastro IT Automation  収集/比較機能 - 実習

### ISSUE THREAD

**Issue by y-masaya3210** [exastro-suite/it-automation-docs#401]

**Comment by sinatommy** [comment]
Translation→WebDesigner

**Comment by ooif** [comment]
v1.8.0でプルリク
[【Learn】v1.8_Exastro IT Automation 収集/比較機能 - 実習](https://github.com/exastro-suite/it-automation-docs/issues/609)
