### ISSUE TITLE
【マニュアル】ファーストステップガイドについて

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation-docs#489]
ファーストステップガイドでは、
•Conductorがワークフローと表現されている。ジョブフローのほうが良いと思う。
•Movementが作業パターンと表現されている。ジョブの方がわかりやすいと思う。
•コンソール一覧にTerraformコンソールなどが抜けているように見える
•最後の方の2回目以降は、という説明のところ、作業対象ホスト、代入値管理を手動で入れる手順になってしまっている。(QiitaのクイックスタートVer1.7.1みたいにできないか？)
など、改善ポイントをご報告しておきます。
ご確認いただければ幸いです。

**Comment by sinatommy** [comment]
ファーストステップガイドを廃止するため、対応無し。
