### ISSUE TITLE
【Learn】_v1.7.1_Exastro IT Automation 収集/比較機能 - 座学/実習の公開

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation-docs#502]
ITAのLearnに新規で収集/比較機能 の 座学/実習が追加になります。
日本語版、英語版それぞれのLearn資料が完了次第、コメントにて声がけしますので、コミュニティサイトへ公開をお願いします。

[【Learn】_v1.7.1_Exastro IT Automation 収集/比較機能 - 座学 #400](https://github.com/exastro-suite/it-automation-docs/issues/400)
[【Learn】_v1.7.1_Exastro IT Automation 収集/比較機能 - 実習 #401](https://github.com/exastro-suite/it-automation-docs/issues/401)

**Comment by ooif** [comment]
説明文はこちら
---
IT Automationの「収集機能・比較機能」の利用手順をご用意しました。
「収集機能・比較機能」では、システムから設定値を収集することや、それを他のデータと比較することが可能になります。

本書は、概要説明と機能紹介の「座学編」、簡単にハンズオンしたい方のための「実習編」の２部構成となっております。

**Comment by ooif** [comment]
@katokeita 
実習編もマージしましたので、公開をお願いいたします。
[【Learn】v1.8_Exastro IT Automation 収集/比較機能 - 実習](https://github.com/exastro-suite/it-automation-docs/issues/609)

**Comment by katokeita** [comment]
実習編公開しました。
https://exastro-suite.github.io/it-automation-docs/learn_ja.html#collectContrast
