### ISSUE TITLE
【Learn】_v1.7.1_Exastro IT Automation Terraformとの連携 - 座学/実習の公開

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation-docs#503]
ITAのLearnに新規でTerraformとの連携の 座学/実習が追加になります。
日本語版、英語版それぞれのLearn資料が完了次第、コメントにて声がけしますので、コミュニティサイトへ公開をお願いします。

[【Learn】_v1.7.1_Exastro IT Automation Terraformとの連携 - 座学 #397](https://github.com/exastro-suite/it-automation-docs/issues/397)
[【Learn】_v1.7.1_Exastro IT Automation Terraformとの連携 - 実習 #398](https://github.com/exastro-suite/it-automation-docs/issues/398)

**Comment by Satoshi-asano** [comment]
日本語版の公開をお願いいたします。
ITA-Terraform-Driver_ja.pdf
ITA-Terraform-Driver_ja.pptx

以下は説明文です。
ーーーーーーーーーーーーーーーーーーーーーー
Terraformとの連携
IT Automationの「Terraform Driver」の利用手順をご用意しました。
Terraform Enterprise/Terraform CloudをExastro経由で実行する場合に必須の機能です。

本書は、概要説明と機能紹介の「座学編」、簡単にハンズオンしたい方のための「実習編」の２部構成となっております。

**Comment by Satoshi-asano** [comment]
日本語版実習編が完成しましたので、公開お願いいたします。
ITA-Terraform-driver-practice_ja.pdf
ITA-Terraform-driver-practice_ja.pptx

**Comment by katokeita** [comment]
実習編公開しました。
https://exastro-suite.github.io/it-automation-docs/learn_ja.html#terraform
