### ISSUE TITLE
【RestAPI】指定例が誤っているように見えます

### ISSUE THREAD

**Issue by dai-kagino** [exastro-suite/it-automation-docs#519]
# 内容
【ITA_利用手順マニュアル RestAPI】の以下記載が誤っているように思われます。
Page14～Page15
(4) EDIT(X-Command)
例(1) 登録
<pre>
▽JSON 形式
[
    {
        "0": {
            "0": "登録",
            "1": "",
            "2": "",
    ・・・（中略）・・・
        }
    }
]
</pre>
この記載方法の場合（複数条件をDICT形式で記載する場合）、最外装のリスト表記（[]）は不要ではないでしょうか？

**Comment by sinatommy** [comment]
修正済み
