### ISSUE TITLE
Learn資料修正_v1.5.0_ITA BASE・座学編

### ISSUE THREAD

**Issue by ryohei-nako** [exastro-suite/it-automation-docs#60]

**Comment by ryohei-nako** [comment]
資料作成済。レビュー待ち

**Comment by suzuko-f** [comment]
修正した箇所
  【全体】
    ・「メインメニュー」画像等をv1.5版に更新
    ・v1.5から追加されたメニューグループ「Symphony」「Conductor」を反映
    ・「メニューグループ >> メニュー >> サブメニュー」を明記する
    ・スライドのフォーマット統一
    ・センタリングや画像のレイヤー修正
  【目次】
    ・「管理コンソール」→「管理コンソール・エクスポート/インポート」
    ・「基本コンソール」→「基本コンソール・Symphony」
    ・「メニューエクスポート/インポート」→「エクスポート/インポート」
  【P4】
    ・「管理コンソール」、「基本コンソール」の２メニューグループに
      「エクスポート/インポート」、「Symphony」を追加し4メニューグループで記述する
  【P5】
    ・「管理コンソール」の作業フローを
      「管理コンソール・エクスポート/インポート」の作業フローに書き換え
  【P6】
    ・「基本コンソール」の作業フローを
      「基本コンソール・Symphony」の作業フローに書き換え
  【P 7,9,13,15,18,20,24】
    ・フローの更新
  【P22】
    ・ほかのスライドに登場しない「Movement領域」というワードの削除および
      ワードが無くても説明できるよう記載を変更
  【P26】
    ・「説明文」と「（画像のつぶれた文字の）強調」で書式を分ける
