### ISSUE TITLE
【Learn】v1.8_Exastro IT Automation 収集/比較機能 - 座学

### ISSUE THREAD

**Issue by y-masaya3210** [exastro-suite/it-automation-docs#608]

**Comment by ooif** [comment]
@katokeita 
収集比較機能【座学編】はv1.7.2→v1.8.0でファイル名が変わってますので、html書き換えの必要などがありましたらご対応お願いいたします。
ITA-collect-contrast_classroom_lecture_ja.pdf（pptx）　→　ITA-collect-compare_classroom_lecture_ja.pdf（pptx）

**Comment by katokeita** [comment]
ファイル名、HTML側修正しました。
