### ISSUE TITLE
Learn資料修正_v1.5.0_ITA BASE_実習編

### ISSUE THREAD

**Issue by ryohei-nako** [exastro-suite/it-automation-docs#61]

**Comment by ryohei-nako** [comment]
作成済み、レビュー待ち

**Comment by suzuko-f** [comment]
修正した箇所
  【全体】
      ・スライドのフォーマット統一（同様の説明内容に対し前半後半で書式に差異があるため）
      ・「メニューグループ >> メニュー >> サブメニュー」を明記する
      ・テキストを「パンくずリスト」「箇条書き」「手順項番（①、②…）」に整える
      ・画像の吹き出しの書式を変更
        （赤枠に対して白ふちの吹き出しだと枠線が途絶えるため関連が切れるように見える）
      ・「Point」の中身が設定値である場合、「手順項番（①、②…）」で記載する
      ・同タイトルで複数スライドにまたがる場合 "(x/x)" という表記を追加する
      ・スライド右のフロー画像の位置がスライドに寄り変わるため位置を統一する
  【P16】
    ・フローがグレーアウトしているように見えたため書式変更
