### ISSUE TITLE
Learn資料修正_v1.5.0_ITA Ansible-Driver_座学編

### ISSUE THREAD

**Issue by ryohei-nako** [exastro-suite/it-automation-docs#62]

**Comment by ryohei-nako** [comment]
作成済、レビュー待ち

**Comment by suzuko-f** [comment]
【全体】
    ・「メインメニュー」画像をv1.5版に更新
    ・句読点の統一
    ・スライドのフォーマット統一
    ・センタリングや画像のレイヤー修正
  【P3】
    ・「実習編（作成中）」→「実習編」に変更
