### ISSUE TITLE
ファーストステップガイドの記載が誤り？

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation-docs#626]
![image](https://user-images.githubusercontent.com/49502353/125214017-ca0f6600-e2ef-11eb-84fe-51ca38f79b7a.png)

ファーストステップガイドの9/21ページの図について、

「コンソールメニューグループ名」は、「メニューグループ名」ではないかと思います。
(「コンソールメニューグループ名」という言葉は聞いたことがありません。)

あと、
「サブメニュー」と記載のところは、「メニュー」ではないでしょうか？

「サブメニュー」は、メニュー操作部に並んでいる、説明、表示フィルタ、・・・のことだと思います。
なので、左にならんでいるのは、「サブメニュー」ではなく「メニュー」であると思います。

**Comment by sinatommy** [comment]
![image](https://user-images.githubusercontent.com/59553555/125399851-1a6bee00-e3ec-11eb-887d-e1f0e950772a.png)

P5記載の「構成管理メニュー作成ガイド」が存在しない。
「利用手順マニュアル　メニュー作成機能」に要修正？

**Comment by sinatommy** [comment]
ファーストステップガイド廃止のためCLOSE
