### ISSUE TITLE
システム構成／環境構築ガイド基本編に情報が不足しているように見えます

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/it-automation-docs#655]
Exastro-ITA_システム構成／環境構築ガイド_基本編.pdf
https://exastro-suite.github.io/it-automation-docs/asset/Documents_ja/Exastro-ITA_%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E6%A7%8B%E6%88%90%EF%BC%8F%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89%E3%82%AC%E3%82%A4%E3%83%89_%E5%9F%BA%E6%9C%AC%E7%B7%A8.pdf

「2.2 システムの通信要件」
に通信要件がリスト化されていますが、このリストに、

①Ansible Towerの場合にどうなるのかわからない

②Terraform Cloudの場合にどうなるのかわからない

といった恰好で、情報が不足しているように見えます。

Ansible Tower、Terraform Cloudの導入の相談を多く受けており、
できるだけ早く、情報の追記を期待致します。

**Comment by j-kumamoto** [comment]
指摘の箇所についてシステム構成と通信要件を見直し、
Ansible-driver編 と Terraform-driver編に通信要件を追加しました。

【主な修正】
●Exastro-ITA_システム構成／環境構築ガイド_Ansible-driver編
・2.1 システム構成　⇒　全面的に文言修正、構成図修正
・2.2 システムの通信要件　⇒　追加
・文言統一
　・Ansible RestAPI → Ansible Core

●Exastro-ITA_システム構成／環境構築ガイド_Terraform-driver編
・2.1 システム構成　⇒　全面的に文言修正、構成図修正
・2.2 システムの通信要件　⇒　追加

●Exastro-ITA_システム構成／環境構築ガイド_基本編
・2.1 システム構成
　⇒　一部文言見直し、オールインワン構成／HA構成の一部修正
