### ISSUE TITLE
[docs]【基本コンソール】機器一覧のAnsible利用情報の追加オプションにCiscoIOS特権モードのパスワードを暗号化して登録したい。

### ISSUE THREAD

**Issue by ooif** [exastro-suite/it-automation-docs#697]
[【基本コンソール】機器一覧のAnsible利用情報の追加オプションにCiscoIOS特権モードのパスワードを暗号化して登録したい。](https://github.com/exastro-suite/it-automation/issues/227)

**Comment by enoman** [comment]
完了
