### ISSUE TITLE
 [docs]【ログ】マニュアル記載のログファイル名の形式が間違っている

### ISSUE THREAD

**Issue by mtakahashiif** [exastro-suite/it-automation-docs#737]
[ログ一覧のマニュアル](https://exastro-suite.github.io/it-automation-docs/asset/Documents_ja/Exastro-ITA_%E3%80%90%E5%8F%82%E8%80%83%E3%80%91%E3%83%AD%E3%82%B0%E4%B8%80%E8%A6%A7.pdf)ではログのフォーマットは以下のように記載されているが、

```
/var/log/httpd/exastro-it-automation-*.log 
```

実機を確認すると、実際には以下が正しい。

```
/var/log/httpd/exastro-it-automation-*_log
/var/log/httpd/exastro-it-automation-*_log-日付
```

**Comment by ta-matsuo** [comment]
v1.8で修正
