### ISSUE TITLE
[docs]【基本機能？】ログインしているユーザに、自分が持っているロールをわからせてあげたほうがよいのではないか？

### ISSUE THREAD

**Issue by ooif** [exastro-suite/it-automation-docs#758]
[【基本機能？】ログインしているユーザに、自分が持っているロールをわからせてあげたほうがよいのではないか？](https://github.com/exastro-suite/it-automation/issues/673)

**Comment by suzuko-f** [comment]
対象ドキュメント_15件

 1.Exastro-ITA_システム構成／設定ガイド_SSO（シングルサインオン）編.pdf
   修正対象：2件
 
 2.Exastro-ITA_利用手順マニュアル_管理コンソール.pdf
  修正対象：25件

 3.Exastro-ITA_利用手順マニュアル_基本コンソール.pdf
  修正対象：7件
  
 4.Exastro-ITA_利用手順マニュアル_エクスポート／インポート.pdf
  修正対象：11
  
 5.Exastro-ITA_利用手順マニュアル_Symphony.pdf
  修正対象：9
  
 6.Exastro-ITA_利用手順マニュアル_Conductor.pdf
  修正対象：11
  
 7.Exastro-ITA_利用手順マニュアル_データレコード毎のロールベースアクセス制御.pdf
  修正対象：34
  
 8.Exastro-ITA_利用手順マニュアル_メニュー作成機能.pdf
  修正対象：47
  
 9.Exastro-ITA_利用手順マニュアル_比較機能.pdf
  修正対象：4
  
10.Exastro-ITA_利用手順マニュアル_ホストグループ機能.pdf
  修正対象：7
  
11.Exastro-ITA_利用手順マニュアル_Ansible-driver.pdf
  修正対象：23
  
12.Exastro-ITA_利用手順マニュアル_収集機能.pdf
  修正対象：2
  
13.Exastro-ITA_利用手順マニュアル_Cobbler-driver.pdf
  修正対象：4
  
14.Exastro-ITA_利用手順マニュアル_Terraform-driver.pdf
  修正対象：16
  
15.Exastro-ITA_利用手順マニュアル_CICD_For_IaC機能.pdf
  修正対象：5
