### ISSUE TITLE
[docd]【Terraform-Driver】「Movement-Module紐付」のレコードを廃止しても「代入値自動登録」の変数名が表示されている

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation-docs#782]
[【Terraform-Driver】「Movement-Module紐付」のレコードを廃止しても「代入値自動登録」の変数名が表示されている](https://github.com/exastro-suite/it-automation/issues/1630)

**Comment by HibikiNanri** [comment]
対応不要のためクローズ。
