### ISSUE TITLE
[docs]【メニュー作成】RBAC機能追加前のバージョンで作ったメニューを「編集」できない

### ISSUE THREAD

**Issue by HibikiNanri** [exastro-suite/it-automation-docs#832]
RBAC機能が追加されたv1.6.0より前のバージョン（v1.5以前）で作成したメニューについて、
バージョンアップ後にメニュー作成の「編集」を実行するとアクセス許可ロール用のカラムが存在しないため以下のエラーとなる。
>SQLの実行が失敗しました。SQLエラー=[Array
(
[0] => 42S22
[1] => 1054
[2] => Unknown column 'TAB_A.ACCESS_AUTH' in 'field list'
)
]

一度でも「初期化」を実行すればアクセス許可ロール用のカラム「ACCESS_AUTH」が追加されるためこの問題は解消される。
RBAC機能が追加される前のバージョン（v1.5以前）で作成したメニューを「編集」したい場合は、一度「初期化」をする必要がある旨をマニュアルに記載する。

**Comment by sinatommy** [comment]
関連issue
[【メニュー作成】RBAC機能追加前のバージョンで作ったメニューを「編集」できない](https://github.com/exastro-suite/it-automation/issues/1730)

**Comment by HibikiNanri** [comment]
v1.8.0, v1.8.1, v1.8.2, v1.9.0にて修正を行ったため、以下は対応しない。
>RBAC機能が追加される前のバージョン（v1.5以前）で作成したメニューを「編集」したい場合は、一度「初期化」をする必要がある旨をマニュアルに記載する。
