### ISSUE TITLE
[docs]【Ansible-Driver】Ansible Towerのバージョン3.8及びAnsible Automation Platform1.2.5でIsolated Nodeの仕組みが廃止

### ISSUE THREAD

**Issue by enoman** [exastro-suite/it-automation-docs#848]
Ansible Towerのバージョン3.8及びAnsible Automation Platform1.2.5では、クラスタ構成を構築する際にIsolated Nodeの仕組みが廃止されています。
この旨をマニュアルに追記

**Comment by ta-matsuo** [comment]
対応無しのためクローズ。
