### ISSUE TITLE
Learn資料作成_Ansibleとの連携（座学編）

### ISSUE THREAD

**Issue by j-kumamoto** [exastro-suite/it-automation-docs#9]
Learn資料作成とコミュニティサイトへの反映

●Ansible-driver 座学編の資料作成
以下の4編を作成予定
①Ansible-driver　概要／共通
②Ansible-Legacy
③Ansible-LegacyRole
④Ansible-Pioneer

**Comment by ryohei-nako** [comment]
作成進行中。
各ansibleメニュごとの簡易的な座学概要を作成中

**Comment by ryohei-nako** [comment]
作成、リリース済み
