### ISSUE TITLE
ITAのコンテナのREADMEの英語版を作成する

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/it-automation-docs#954]
[ITAコンテナのREADME.md](https://github.com/exastro-suite/it-automation-container)の英語版を作成する。

**Comment by JoachimLarsen** [comment]
お待たせしております。翻訳完成できました。
ファイルはこちらになります。どうぞご確認ください。
[# Using Exastro IT Automation's Container.md](https://github.com/exastro-suite/it-automation-docs/files/8378746/Using.Exastro.IT.Automation.s.Container.md)

不明点等ございましたら連絡をください。

**Comment by sinatommy** [comment]
掲載完了
https://github.com/exastro-suite/it-automation-container/blob/main/README.en.md
