### ISSUE TITLE
[docs]【Ansible共通】ファイル管理、テンプレート管理のアップロードファイル名を「スペース」や「 ()」にすると作業実行時エラーになる

### ISSUE THREAD

**Issue by d-miyata** [exastro-suite/it-automation-docs#961]
[【Ansible共通】ファイル管理、テンプレート管理のアップロードファイル名を「スペース」や「 ()」にすると作業実行時エラーになる](https://github.com/exastro-suite/it-automation/issues/1854)

**Comment by enoman** [comment]
完了
